### ISSUE TITLE
分析结果的 html 文件是纯文本样式

### ISSUE THREAD

**Issue by no-trouble** [harddog/oclint_apply#1]
# 生成报表
`oclint-json-compilation-database ${exclude} -- \
-report-type xcode \
`
此处的 -report-type xcode 输出格式为 xcode，是否是 html 文件显示为纯文本的原因；如果是的话，可不可以改为 html 。

**Comment by doge1024** [comment]
是的，如果你想输出html格式的文件，需要将命令改为 `-report-type html `


官方文档支持导出的文件[类型](http://docs.oclint.org/en/stable/howto/selectreporters.html)
[iOS使用OCLint做静态代码分析](https://www.jianshu.com/p/4f505e92d557)
